# 第四次作业及一些相关的知识

## numpy的一些矩阵操作

可以参考：https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [8]:
import numpy as np

# 生成 1 到 -1 之间的一个均匀分布
a = 2*np.random.random(size=12).reshape((2,3,2)) - 1  # 注意减一操作是广播到所有元素

# 生成 均值0 方差0.2 的一个正太分布
b = np.random.normal(0,0.2,12)  

print('a = ', a)
print('b = ', b)

a =  [[[ 0.61030141 -0.40265278]
  [ 0.26385643 -0.68264247]
  [-0.61721161 -0.47694042]]

 [[ 0.17575284 -0.73074758]
  [ 0.54945274  0.75470361]
  [ 0.18467625  0.95093941]]]
b =  [ 0.0216128   0.10229882 -0.20085613  0.13157968 -0.25259319 -0.09328452
  0.16744237 -0.00412888  0.24321142  0.02801617  0.04308529  0.4075351 ]


请你创建三个矩阵$A, B, C$，它们都是服从标准正太分布的矩阵，其中$A$的大小为$200\times 400$，$B$的大小为$400\times 400$，$C$的大小为$400\times 1$.

In [16]:
import numpy as np
np.random.seed(1)

'''
添加你的代码
'''
A = np.random.normal(0,1,80000).reshape(200,400)
B = np.random.normal(0,1,160000).reshape(400,400)
C = np.random.normal(0,1,400).reshape(400,1)
print(A)
print(B)
print(C)

[[ 1.62434536 -0.61175641 -0.52817175 ...  0.92061512 -0.03536792
   2.11060505]
 [-1.30653407  0.07638048  0.36723181 ... -0.7029204   0.72555052
  -0.32420422]
 [ 0.81434313  0.78046993 -1.46405357 ... -1.44899155  0.77949187
  -1.08630091]
 ...
 [ 0.38623824 -2.02630464 -0.07927278 ...  1.32802528  0.84477187
  -2.97708769]
 [ 1.06187594  0.27194716 -0.13475197 ... -1.6002075  -0.32644922
  -0.75042092]
 [-0.88539348 -1.85818743  0.98523221 ... -0.36830296  1.67951517
   0.08093327]]
[[ 1.27900677 -0.16162266 -0.62874648 ... -0.28675657  1.74837802
   0.11288292]
 [-1.76704958  0.12958642  1.97277595 ... -0.68250606  0.23693318
  -1.14846976]
 [-0.74690544  0.89184265  0.70002481 ...  0.50982408 -2.29283754
  -0.821319  ]
 ...
 [-0.17656439  0.17627417 -0.57809651 ...  0.72066532 -0.32557575
   1.82349058]
 [-1.08192446  0.95902432 -0.88238858 ... -0.39027174  0.69152099
   0.63712368]
 [ 0.19950216  0.6074437  -0.96185493 ... -0.96066284 -1.21737348
   1.23494832]]
[[ 0.03566559]
 

### 1.计算$A+A$,$AA^T$,$A^TA$,$AB$. 然后写一个函数对于参数$\lambda$，计算$A(B-\lambda I)$.

In [17]:
# 作业：添加你的代码

#A+A
print(A+A)

#AA^T
print(A.dot(A.T))

#A^TA
print(A.T.dot(A))

#AB
print(A.dot(B))

def func(lamda):
    return A.dot(B - lamda * np.eye(lamda))
func(1)

[[ 3.24869073 -1.22351283 -1.0563435  ...  1.84123024 -0.07073585
   4.22121011]
 [-2.61306815  0.15276096  0.73446363 ... -1.40584081  1.45110104
  -0.64840844]
 [ 1.62868626  1.56093986 -2.92810715 ... -2.8979831   1.55898373
  -2.17260181]
 ...
 [ 0.77247648 -4.05260929 -0.15854556 ...  2.65605057  1.68954374
  -5.95417538]
 [ 2.12375189  0.54389432 -0.26950394 ... -3.200415   -0.65289844
  -1.50084184]
 [-1.77078697 -3.71637486  1.97046443 ... -0.73660592  3.35903033
   0.16186653]]
[[382.25123513  19.72579261  -5.41044944 ... -11.15580832  -2.57787009
   29.07521085]
 [ 19.72579261 417.07037671   3.07525367 ...   1.54493692  -3.17868633
  -19.26238669]
 [ -5.41044944   3.07525367 366.01687564 ...   2.93460707  13.78076981
   19.34408635]
 ...
 [-11.15580832   1.54493692   2.93460707 ... 394.55092866 -13.88828895
    9.21249118]
 [ -2.57787009  -3.17868633  13.78076981 ... -13.88828895 421.44500824
    2.31851487]
 [ 29.07521085 -19.26238669  19.34408635 ...   9.21249118   2.318514

array([[-42.23100612, -26.97261953, -22.36948947, ..., -13.6025539 ,
         -9.61723225,  10.30001903],
       [ 16.4139066 ,  11.6979127 ,  16.15426066, ..., -17.61115581,
        -22.91437368,  -3.05497145],
       [ 14.76790131,   3.55244527,  12.65323577, ...,  13.26245113,
        -40.07220198, -41.43485033],
       ...,
       [  4.23939805,  10.6026592 ,  -9.30044555, ...,  12.71076083,
         21.91248547,  -7.29143397],
       [ -0.58910107, -15.07701593,   1.94629197, ..., -54.8050494 ,
        -31.51226524,  -9.94870678],
       [-10.6497373 ,  22.3000132 ,  26.99928107, ...,  14.63804462,
        -15.80543323,  31.59482379]])

### 2.计算$Bx=C$的解。

In [18]:
# 作业：添加你的代码
print(np.linalg.solve(B, C))

[[ 1.17023513e+00]
 [ 7.91923301e-02]
 [ 1.03627019e+00]
 [ 1.31698536e+00]
 [ 6.64161463e-01]
 [ 8.52669085e-01]
 [-1.63681059e-01]
 [-8.01939608e-02]
 [ 7.13867037e-01]
 [-6.87733794e-01]
 [-3.16645240e+00]
 [ 1.74992991e-01]
 [-1.66927168e-01]
 [ 6.38129504e-01]
 [ 1.84899213e+00]
 [ 8.87387556e-01]
 [ 4.74054017e-01]
 [-1.26385541e+00]
 [ 1.44958910e+00]
 [-8.76112515e-01]
 [-2.59192476e-01]
 [-1.75669699e+00]
 [ 3.47985022e-01]
 [ 1.67165805e-02]
 [-1.49648802e+00]
 [ 1.01809581e+00]
 [-5.48098221e-01]
 [ 1.24306178e+00]
 [ 2.46189200e+00]
 [-1.48313049e+00]
 [-1.99573810e+00]
 [ 8.87725167e-02]
 [-5.81202337e-01]
 [ 6.31457634e-01]
 [-2.09560653e+00]
 [-2.21657125e-01]
 [ 5.33056084e-01]
 [ 1.38136543e+00]
 [ 5.36428718e-01]
 [ 2.49467072e+00]
 [-6.28340617e-01]
 [ 1.22226478e+00]
 [ 9.90895614e-01]
 [ 5.61038455e-01]
 [-2.54919618e+00]
 [ 4.85755294e-01]
 [ 1.37773851e+00]
 [-1.75304545e+00]
 [ 1.24841216e+00]
 [-1.47655862e+00]
 [-2.84090551e+00]
 [ 1.66527358e+00]
 [ 3.6595633

## 向量范数

    1-范数： ，即向量元素绝对值之和，matlab调用函数norm(x, 1) 。
    2-范数：，Euclid范数（欧几里得范数，常用计算向量长度），即向量元素绝对值的平方和再开方，matlab调用函数norm(x, 2)。
     ∞-范数：，即所有向量元素绝对值中的最大值，matlab调用函数norm(x, inf)。
     −∞-范数：，即所有向量元素绝对值中的最小值，matlab调用函数norm(x, -inf)。
    p-范数：，即向量元素绝对值的p次方和的1/p次幂，matlab调用函数norm(x, p)。

## 矩阵范数

    1-范数：， 列和范数，即所有矩阵列向量绝对值之和的最大值，matlab调用函数norm(A, 1)。
    2-范数：，为的最大特征值。，谱范数，即A'A矩阵的最大特征值的开平方。matlab调用函数norm(x, 2)。-范数：，行和范数，即所有矩阵行向量绝对值之和的最大值，matlab调用函数norm(A, inf)。
    F-范数：，Frobenius范数，即矩阵元素绝对值的平方和再开平方，matlab调用函数norm(A, ’fro‘)。
    核范数：是A的奇异值。

矩阵范数：矩阵A的2范数就是 A的转置乘以A矩阵特征根 最大值的开根号； 向量范数：向量x的2范数是x中各个元素平方之和再开根号； 函数范数：函数f(x)的2范数是x在区间（a,b）上f(x)的平方的积分再开根号。

2-范数：║A║2 = A的最大奇异值 = ( max{ λi(A*A^H) } ) ^{1/2} (欧几里德范数,谱范数,即AA'特征值λi中最大者λ1的平方根，其中A^H为A的转置共轭矩阵)。

引自： https://cloud.tencent.com/developer/article/1101927

### 3.计算$A$的Frobenius范数$||A||_F$、$B$的无穷范数$||B||_\infty$。

In [19]:
# 作业：添加你的代码
print(np.linalg.norm(A, 'fro'))
print(np.linalg.norm(B, np.inf))

282.76087776669334
354.96933099772764


### 矩阵特征值

numpy的矩阵特征值计算提供了两组函数，一组用于通用的矩阵，一组用于赫米特矩阵。另外，每组中又包含两个函数，分别用于只计算特征值，以及特征向量。

1. `w, v = np.linalg.eig(a)`，计算一个方阵的特征值和特征向量，其中特征向量v是归一化后的向量。
2. `w, v = np.linalg.eigh(a, UPLO='L')`，用于赫米特矩阵的特征值计算。其中`UPLO`的取值`L`与`U`分别表示计算时采用`a`的下三角还是上三角矩阵。
3. `w = np.linalg.eigvals(a)`，与1.的最大差别就是没有计算特征向量。
4. `w = np.linalg.eigvalsh(a)`，与2.的最大差别就是没有计算特征向量。

### 4.求解 $B^TB$的特征值的最大和最小值以及对应的特征向量。

In [20]:
# 作业：添加你的代码

C = B.T.dot(B)
w, v = np.linalg.eig(C)
print(w[0])
print(v[0])
print(w[-1])
print(v[-1])

1552.3296608208384
[-3.46490369e-02  6.32369369e-02  3.62709006e-02  1.05563282e-02
  5.95645566e-02 -2.90291043e-02  2.85958494e-02 -8.49125697e-02
  5.54956915e-02 -5.62415770e-05 -1.56603398e-02  2.74868691e-02
  2.98279236e-02 -4.13464865e-02  4.47852016e-02 -4.77973173e-03
 -6.76800730e-03  1.12455549e-01  1.48257615e-02 -5.75712895e-02
 -7.63177241e-02 -6.49999616e-02 -8.43551617e-03  1.13239311e-01
  5.28895138e-03  1.11265924e-01  3.68328419e-02  8.30351441e-02
  1.37244986e-02 -1.67981960e-01  9.16971207e-03  4.41738563e-02
  3.14367510e-02  1.46070225e-02  1.29668834e-01 -3.58751001e-04
 -1.15766283e-02 -4.92357547e-02 -3.86920299e-03 -5.48370626e-02
 -8.63929454e-02 -3.81628959e-02 -6.02538831e-02  8.11948551e-02
  1.47549849e-01 -2.22882905e-03  1.75878493e-02 -3.52409138e-02
 -6.83023685e-02  4.59785069e-02  4.00239514e-02 -6.58801520e-03
 -3.68277992e-02 -1.15353368e-01 -4.88414658e-03 -7.60965634e-02
 -7.05304412e-02  6.16730270e-02 -1.61211843e-02  3.61865848e-02
 -6.31

# 奇异值分解（SVD）

SVD将原始的矩阵$Data$分解成三个矩阵$U$,$\Sigma$,和$V^T$，如果原始矩阵$Data$是$m$行$n$列，那么$U$,$\Sigma$,和$V^T$就分别是$m$行$m$列、$m$行$n$列和$n$行$n$列。

为了清晰起见，上述过程可以写成如下一行：$$Data_{m\times n}=U_{m\times m}\Sigma_{m \times n}V^T_{n\times n}$$

上述分解中会构建出一个矩阵$\Sigma$，该矩阵只有对角元素，其他元素均为0. 另一个惯例就是，$\Sigma$的对角元素是从大到小排列的。这些对角元素称为奇异值（Singular Value），它们就是矩阵$Data Data^{T}$特征值的平方根。

在科学工程中，一直存在这样一个普遍事实：在某个奇异值的数目（$r$个）之后，其他的奇异值都置为0.这就意味着数据集中仅有$r$个重要特征，而其余特征则都是噪声或冗余特征。

In [16]:
import numpy as np
U, Sigma, VT = np.linalg.svd([[1, 1], [7, 7]])
print('U = ', U)
print('Sigma = ', Sigma)
print('VT = ', VT)

U =  [[-0.14142136 -0.98994949]
 [-0.98994949  0.14142136]]
Sigma =  [1.00000000e+01 2.82797782e-16]
VT =  [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


可以看到矩阵$\Sigma$是以对角线元素组成的行向量返回。

接下来我们再来看一个更大的例子。

In [21]:

data = [[1, 1, 1, 0, 0],
        [2, 2, 2, 0, 0],
        [1, 1, 1, 0, 0],
        [5, 5, 5, 0, 0],
        [1, 1, 0, 2, 2],
        [0, 0, 0, 3, 3],
        [0, 0, 0, 1, 1]]

U, Sigma, VT = np.linalg.svd(data)
print(Sigma)

[9.72140007e+00 5.29397912e+00 6.84226362e-01 4.11502614e-16
 1.36030206e-16]


可以看到$\Sigma$中前3个数值比其他的值大了很多，说明前3个奇异值蕴含了矩阵中大量的特征信息，所以我们就可以用如下结果来近似原矩阵
$$Data_{m\times n}\approx U_{m\times 3}\Sigma_{3 \times 3}V^T_{3\times n}$$
<img src="1.jpeg" width="40%">

### 请你写一写用三个奇异值来近似原矩阵的代码
（即计算$U_{m\times 3}\Sigma_{3 \times 3}V^T_{3\times n}$）

In [22]:
# 作业：添加你的代码
diagSigma = np.diag(Sigma)
row = diagSigma[0:4]
new = row[:,0:4]
A = U.T[0:4].T.dot(new).dot(VT[0:4])
print(A)

[[ 1.00000000e+00  1.00000000e+00  1.00000000e+00  6.08214551e-16
   9.39362853e-16]
 [ 2.00000000e+00  2.00000000e+00  2.00000000e+00  5.25086990e-16
   5.32601824e-17]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00  2.47907926e-16
   1.78700965e-16]
 [ 5.00000000e+00  5.00000000e+00  5.00000000e+00 -3.19927507e-17
   4.91905876e-17]
 [ 1.00000000e+00  1.00000000e+00 -5.48397422e-16  2.00000000e+00
   2.00000000e+00]
 [ 3.20560528e-16  4.44321467e-16 -3.48967188e-16  3.00000000e+00
   3.00000000e+00]
 [ 9.97465999e-17  1.43114687e-16 -1.66533454e-16  1.00000000e+00
   1.00000000e+00]]


可以看到，只用3个奇异值我们就很大程度上近似出了原矩阵，这也就是用SVD图片压缩的实现方法。

我们是如何知道仅需保留3个奇异值的呢？一种简单的方法是直接规定奇异值的数量，但是这样我们就没有把奇异值的分布情况考虑进去，有的图可能只有一个特别大的奇异值，有的图可能奇异值大小都比较平均。

确定要保留的奇异值的数目有很多启发式策略，其中一个典型的做法就是保留矩阵中90%的能量信息。

为了计算总能量信息，我们将所有的奇异值平方后求和。于是可以将奇异值的平方和从大到小累加到总值的90%为止。

接下来我们来看一个将SVD应用于图像压缩的例子。通过TKinter可视化的方式，我们将会很容易看到SVD对数据近似的效果。

# 基于SVD的图像压缩 + Tkinter库可视化

### 目标：
1. 使用TKinter来可视化压缩后的图片。（框架已经写好）
2. 要求有一个输入框用来输入保留的奇异值个数，要求默认值是保留90%以上能量的最小奇异值个数。（输入框已经写好，默认值请你计算）
3. 点击“Display“按钮后，显示新的近似图像。（按钮和重构图像需要你来实现，分别参考tkinter的Button和之前讲的SVD）
4. 在近似图像的右边画一张图，表示【奇异值保留的能量百分比】与【奇异值个数】的关系。（需要你来实现，参考plt的使用方法）
5. 在显示近似图像的时候，显示保留的奇异值个数和奇异值保留的能量百分比。（需要你来实现，参考tkinter的Label）
6. （选做）增加一个输入框或者就在原输入框中输入[0.0, 1.0]的小数，显示保留这么多能量情况下的近似图片。

下图是一个可能的例子（不用做到完全一样），不过这里第2\5\6点还未实现。

<img src="2.png" width="60%">

### 注意：
   
- 图片是三通道的，转化为numpy array的时候可以看到形状是$height \times width \times 3$，对三个矩阵都做一次SVD即可。
- 第2点中的最小奇异值个数用三个通道各自的最小值的最大值来表示。
- 代码可以随意改，这里只是提供了一个可行的框架，实现功能即可。

### 检查要点：
- 要有“Display“按钮，且点击之后图片会根据输入框里的值重新近似并显示。
- 输入框默认值正确（只要不相差太多都算对）。
- 保留能量百分比与奇异值个数的关系图画的趋势接近就算正确。
- 在界面中可以看到当前的图片中保留了几个奇异值和保留的能量百分比。

In [23]:
import numpy as np
from PIL import Image

img = Image.open("example.jpeg")
arr = np.array(img)  # [height, width, channel(3)]

In [24]:
number = []
energy = []

'''
根据rate计算图片保留的奇异值个数
'''
def caculate_numSV(arr, list1, list2, rate=0.9):

    U0, Sigma0, VT0 = np.linalg.svd(arr[:,:,0])
    U1, Sigma1, VT1 = np.linalg.svd(arr[:,:,1])
    U2, Sigma2, VT2 = np.linalg.svd(arr[:,:,2])

    wholeValue = 0

    for i in range(len(Sigma0)):
        wholeValue += Sigma0[i] ** 2

    for i in range(len(Sigma1)):
        wholeValue += Sigma1[i] ** 2

    for i in range(len(Sigma2)):
        wholeValue += Sigma2[i] ** 2

    count = 0
    sumofs = 0
    flag = True
    for i in range(len(Sigma0)):
        count += 1
        sumofs += Sigma0[i] ** 2
        sumofs += Sigma1[i] ** 2
        sumofs += Sigma2[i] ** 2
        list1.append(count)
        list2.append(sumofs / wholeValue)

        if sumofs >= wholeValue * rate and flag:
            flag = False
            output = count
            a = count
            b = sumofs / wholeValue

    return output


def return_arr_by_svd(arr, numSV):

    U, Sigma, VT = np.linalg.svd(arr)
    diagSigma = np.diag(Sigma)
    row = diagSigma[0:numSV + 1]
    new = row[:, 0:numSV + 1]
    return U.T[0:numSV + 1].T.dot(new).dot(VT[0:numSV+1])


'''
根据numSV压缩图片
'''


def compress(arr, numSV):

    myarr = arr.copy()
    for i in range(3):
        myarr[:, :, i] = return_arr_by_svd(myarr[:, :, i], numSV)
    return myarr

In [25]:
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from tkinter import *
from PIL import Image

def display(numSV=10):
    display.f.clf()
    display.a = display.f.add_subplot(121)
    display.b = display.f.add_subplot(122)

    new_arr = compress(arr, numSV)
    img = Image.fromarray(new_arr)
    display.a.imshow(img)

    '''
        在display.b上画出保留能量百分比与奇异值个数的关系：
    '''
    display.b.plot(number, energy)

    Label(root, text="当前奇异值个数:").grid(row=3, column=0)
    Label(root, text="当前能量保留比例:").grid(row=4, column=0)
    Label(root, text="%d" % currentNumber).grid(row=3, column=1)
    Label(root, text="%f" % currentRate).grid(row=4, column=1)
    display.canvas.draw() # 刷新画布


defaultnumSV = caculate_numSV(arr, number, energy, 0.9)
currentNumber = defaultnumSV
currentRate = 0.9

'''
根据输入的奇异值个数来显示图片
'''


def myfunc1():

    number.clear()
    energy.clear()
    tmp = caculate_numSV(arr, number, energy)
    numSV = int(tolNentry.get())
    global currentNumber
    currentNumber = numSV
    global currentRate
    currentRate = energy[numSV]
    display(numSV)

'''
根据输入的能量保留比例来显示图片
'''


def myfunc2():

    number.clear()
    energy.clear()
    rate = float(e.get())

    numSV = caculate_numSV(arr, number, energy, rate)
    global currentNumber
    currentNumber = numSV
    global currentRate
    currentRate = energy[numSV]
    display(numSV)


root = Tk()
root.title("基于SVD的图像压缩")
display.f = Figure(figsize=(6,3), dpi=120) # create canvas
display.canvas = FigureCanvasTkAgg(display.f, master=root)
display.canvas.draw()
display.canvas.get_tk_widget().grid(row=0, columnspan=3)

Label(root, text="按奇异值个数显示图片(default=%d with rate = 0.9)"%defaultnumSV).grid(row=1, column=0)
Label(root, text="按能量百分比显示图片").grid(row=2, column=0)
Label(root).grid(row=3, column=1)
tolNentry = Entry(root)
tolNentry.grid(row=1, column=1)
e = Entry(root)
e.grid(row=2, column=1)

'''
    添加一个Button，使得点击时，根据输入的奇异值个数重新近似图片：
'''
Button(root, text="display", command=myfunc1).grid(row=1, column=2)
Button(root, text="display", command=myfunc2).grid(row=2, column=2)
display(defaultnumSV)

display.canvas.draw()


root.mainloop()
